version: "3"
services:
  postgresql:
    image: postgres:16
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: timetracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql:/var/lib/postgresql/data
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    container_name: liquibase
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/timetracker
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - backend

  app:
    image: openjdk:17-jdk
    container_name: time-tracker-app
    depends_on:
      - postgresql
    ports:
      - "8080:8080"
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: ./gradlew bootRun
    networks:
      - backend

volumes:
  postgresql: {}

networks:
  backend: {}
